# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: job1
  steps:
  - script: echo job1 - hello
    displayname: 'run a 1 line script'
  - script: echo multiline script
     echo line 1
     echo line 2
     echo line 3
- job: job 2
  dependsOn: job1
  steps: 
   - script: echo job 2
     displayName: fsdfasd''
